import type { AppProps } from "next/app";
import Head from "next/head";
import Layout from "~/components/layout";
import "bootstrap/dist/css/bootstrap.min.css";
import "@/styles/globals.scss";

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <Layout>
      <Head>
        <title>HHG BEAUTY</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Component {...pageProps} />
    </Layout>
  );
}

export default MyApp;
