import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import HomeContent from "../components/home";
import Footer from "../components/common/footer";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>HHG BEAUTY</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <HomeContent></HomeContent>
      </main>
    </div>
  );
};

export default Home;
